### ISSUE TITLE
 WARNING Docker image (mlcommons/dataperf:0.0.1) does not exist or build strategy is 'always'

### ISSUE THREAD

**Issue by Zikovich** [harvard-edge/dataperf-speech-example#22]
Dears,

After regards,

I am using colab and i face an error below

```
2022-12-17 14:27:09 61582abe88d2 mlcube_docker.docker_run[592] WARNING Docker image (mlcommons/dataperf:0.0.1) does not exist or build strategy is 'always'. Will run 'configure' phase.
sh: 1: docker: not found
2022-12-17 14:27:09 61582abe88d2 mlcube.shell[592] ERROR Command='docker build  -t mlcommons/dataperf:0.0.1 -f /content/drive/MyDrive/mygithub/dataperf-speech-example/Dockerfile_mlcube /content/drive/MyDrive/mygithub/dataperf-speech-example' status=32512 exit_status=exited exit_code=127 on_error=raise
2022-12-17 14:27:09 61582abe88d2 mlcube.__main__[592] ERROR Failed to run MLCube with error code 127.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mlcube_docker/docker_run.py", line 153, in configure
    Shell.run([docker, 'build', build_args, '-t', image, '-f', recipe, context])
  File "/usr/local/lib/python3.8/dist-packages/mlcube/shell.py", line 95, in run
    raise ExecutionError(
mlcube.errors.ExecutionError: Failed to execute shell command.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mlcube/__main__.py", line 211, in run
    runner.run()
  File "/usr/local/lib/python3.8/dist-packages/mlcube_docker/docker_run.py", line 171, in run
    self.configure()
  File "/usr/local/lib/python3.8/dist-packages/mlcube_docker/docker_run.py", line 155, in configure
    raise ExecutionError.mlcube_configure_error(
mlcube.errors.ExecutionError: DockerRun runner failed to configure MLCube. Error occurred while building docker image (docker=docker, build_args=, image=mlcommons/dataperf:0.0.1, recipe=/content/drive/MyDrive/mygithub/dataperf-speech-example/Dockerfile_mlcube, context=/content/drive/MyDrive/mygithub/dataperf-speech-example).
ERROR:
	message: DockerRun runner failed to configure MLCube.
	description: Error occurred while building docker image (docker=docker, build_args=, image=mlcommons/dataperf:0.0.1, recipe=/content/drive/MyDrive/mygithub/dataperf-speech-example/Dockerfile_mlcube, context=/content/drive/MyDrive/mygithub/dataperf-speech-example).
	context: {'status': 'exited', 'code': 127, 'cmd': 'docker build  -t mlcommons/dataperf:0.0.1 -f /content/drive/MyDrive/mygithub/dataperf-speech-example/Dockerfile_mlcube /content/drive/MyDrive/mygithub/dataperf-speech-example'}
[7]
0s
```

Here is the link of the notebook in any case
https://github.com/harvard-edge/dataperf-speech-example/blob/67279c057ccd8025f6fac7f19ebe340fd5580eee/DataPerfAlgSelection.ipynb

Any Help will is highly appricaiated :)

**Comment by mmaz** [comment]
Hi @Zikovich 

Can you try running our speech example directly in python, without MLCube? In particular, please see these instructions:

https://github.com/harvard-edge/dataperf-speech-example#running-selectioneval-directly

This should work within Google Colab, and allow you to start developing your own selection algorithm.

Since MLCube requires Docker to be installed, and Docker is not officially supported by Colab, I would not suggest trying to use MLCube if you want to work in a Colab environment. We'll clarify our readme to explain that MLCube is not required.

cc @colbybanbury @davidjurado @remg1997
